# [dbo].[Alter_Ego_Person_Temporal_History]

In [0]:
USE [Superheroes]
GO

In [0]:
/****** Object:  Table [dbo].[Alter_Ego_Person_Temporal_History]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Alter_Ego_Person_Temporal_History](
	[Alter_Ego_Person_ID] [int] NOT NULL,
	[Person_ID] [int] NOT NULL,
	[Alter_Ego_ID] [int] NOT NULL,
	[Sys_Start_Time] [datetime2](7) NOT NULL,
	[Sys_End_Time] [datetime2](7) NOT NULL
) ON [PRIMARY]
GO

# [dbo].[Alter_Ego_Person]

In [0]:
/****** Object:  Table [dbo].[Alter_Ego_Person]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Alter_Ego_Person](
	[Alter_Ego_Person_ID] [int] IDENTITY(1,1) NOT NULL,
	[Person_ID] [int] NOT NULL,
	[Alter_Ego_ID] [int] NOT NULL,
	[Sys_Start_Time] [datetime2](7) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
	[Sys_End_Time] [datetime2](7) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
 CONSTRAINT [PK_Alter_Ego_Person] PRIMARY KEY CLUSTERED 
(
	[Alter_Ego_Person_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Alter_Ego_Person] UNIQUE NONCLUSTERED 
(
	[Person_ID] ASC,
	[Alter_Ego_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([Sys_Start_Time], [Sys_End_Time])
) ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[Alter_Ego_Person_Temporal_History])
)
GO

# [dbo].[Alter_Ego]

In [0]:
/****** Object:  Table [dbo].[Alter_Ego]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Alter_Ego](
	[Alter_Ego_ID] [int] IDENTITY(1,1) NOT NULL,
	[Alter_Ego_Name] [varchar](50) NOT NULL,
	[Comic_Universe_ID] [int] NOT NULL,
 CONSTRAINT [PK_Alter_Ego] PRIMARY KEY CLUSTERED 
(
	[Alter_Ego_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_Alter_Ego] UNIQUE NONCLUSTERED 
(
	[Alter_Ego_Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Alter_Ego_Person_History]

In [0]:
/****** Object:  Table [dbo].[Alter_Ego_Person_History]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Alter_Ego_Person_History](
	[Alter_Ego_Person_History_ID] [int] IDENTITY(1,1) NOT NULL,
	[History_Date] [datetime] NOT NULL,
	[ChangeType] [char](1) NOT NULL,
	[Old_Alter_Ego_ID] [int] NULL,
	[Old_Person_ID] [int] NULL,
	[New_Alter_Ego_ID] [int] NULL,
	[New_Person_ID] [int] NULL,
 CONSTRAINT [PK_Alter_Ego_Person_History] PRIMARY KEY CLUSTERED 
(
	[Alter_Ego_Person_History_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Alter_Ego_Person_History] UNIQUE NONCLUSTERED 
(
	[History_Date] ASC,
	[ChangeType] ASC,
	[Old_Alter_Ego_ID] ASC,
	[Old_Person_ID] ASC,
	[New_Alter_Ego_ID] ASC,
	[New_Person_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Comic_Universe]

In [0]:
/****** Object:  Table [dbo].[Comic_Universe]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comic_Universe](
	[Comic_Universe_ID] [int] IDENTITY(1,1) NOT NULL,
	[Comic_Universe_Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Comic_Universe] PRIMARY KEY CLUSTERED 
(
	[Comic_Universe_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_Comic_Universe] UNIQUE NONCLUSTERED 
(
	[Comic_Universe_Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Corporation]

In [0]:
/****** Object:  Table [dbo].[Corporation]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Corporation](
	[Corporation_ID] [int] IDENTITY(1,1) NOT NULL,
	[Corporation_Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Corporation] PRIMARY KEY CLUSTERED 
(
	[Corporation_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_Corporation] UNIQUE NONCLUSTERED 
(
	[Corporation_Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[ETL_Error_Log]

In [0]:
/****** Object:  Table [dbo].[ETL_Error_Log]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ETL_Error_Log](
	[ETL_Error_Log_ID] [int] IDENTITY(1,1) NOT NULL,
	[Error_Description] [varchar](500) NULL,
	[CSV_Data] [varchar](1000) NULL,
	[Error_Timestamp] [datetime] NULL,
 CONSTRAINT [PK_ETL_Error_Log] PRIMARY KEY CLUSTERED 
(
	[ETL_Error_Log_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Gadget]

In [0]:
/****** Object:  Table [dbo].[Gadget]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Gadget](
	[Gadget_ID] [int] IDENTITY(1,1) NOT NULL,
	[Gadget_Name] [varchar](50) NOT NULL,
	[Gadget_Desc] [varchar](254) NULL,
 CONSTRAINT [PK_Gadget] PRIMARY KEY CLUSTERED 
(
	[Gadget_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_Gadget] UNIQUE NONCLUSTERED 
(
	[Gadget_Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Gadget_Order_Form]

In [0]:
/****** Object:  Table [dbo].[Gadget_Order_Form]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Gadget_Order_Form](
	[Order_ID] [int] IDENTITY(1,1) NOT NULL,
	[Order_Date] [datetime] NOT NULL,
	[Person_ID] [int] NOT NULL,
	[Corporation_ID] [int] NULL,
	[Gadget_ID] [int] NOT NULL,
	[Number_Ordered] [int] NOT NULL,
	[Price_Per_Item] [numeric](19, 2) NOT NULL,
	[Tax] [numeric](19, 2) NOT NULL,
	[Shipping] [numeric](19, 2) NOT NULL,
	[Total_Due] [numeric](19, 2) NOT NULL,
 CONSTRAINT [PK_Gadget_Order_Form] PRIMARY KEY CLUSTERED 
(
	[Order_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Gadget_Order_Form] UNIQUE NONCLUSTERED 
(
	[Order_Date] ASC,
	[Person_ID] ASC,
	[Corporation_ID] ASC,
	[Gadget_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Good_Deed_History]

In [0]:
/****** Object:  Table [dbo].[Good_Deed_History]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Good_Deed_History](
	[Good_Deed_History_ID] [int] IDENTITY(1,1) NOT NULL,
	[Good_Deed_Type_ID] [tinyint] NULL,
	[Good_Deed_Person_ID] [int] NULL,
	[Good_Deed_Description] [varchar](250) NULL,
	[Good_Deed_Timestamp] [datetime] NULL,
 CONSTRAINT [PK_Good_Deed_History] PRIMARY KEY CLUSTERED 
(
	[Good_Deed_History_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Good_Deed_Type]

In [0]:
/****** Object:  Table [dbo].[Good_Deed_Type]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Good_Deed_Type](
	[Good_Deed_Type_ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[Good_Deed_Type_Name] [varchar](50) NULL,
 CONSTRAINT [PK_Good_Deed_Type] PRIMARY KEY CLUSTERED 
(
	[Good_Deed_Type_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[MSSQL_TemporalHistoryFor_725577623]

In [0]:
/****** Object:  Table [dbo].[MSSQL_TemporalHistoryFor_725577623]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MSSQL_TemporalHistoryFor_725577623](
	[Alter_Ego_Person_ID] [int] NOT NULL,
	[Person_ID] [int] NOT NULL,
	[Alter_Ego_ID] [int] NOT NULL,
	[Sys_Start_Time] [datetime2](7) NOT NULL,
	[Sys_End_Time] [datetime2](7) NOT NULL
) ON [PRIMARY]
GO

# [dbo].[Person]

In [0]:
/****** Object:  Table [dbo].[Person]    Script Date: 8/17/2022 8:16:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[Person_ID] [int] IDENTITY(1,1) NOT NULL,
	[First_Name] [varchar](50) NOT NULL,
	[Last_Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[Person_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [DF_Alter_Ego_Person_Alter_Ego_ID]

In [0]:
ALTER TABLE [dbo].[Alter_Ego_Person] ADD  CONSTRAINT [DF_Alter_Ego_Person_Alter_Ego_ID]  DEFAULT ((1)) FOR [Alter_Ego_ID]
GO

# [DF_Alter_Ego_Person_History_History_Date]

In [0]:
ALTER TABLE [dbo].[Alter_Ego_Person_History] ADD  CONSTRAINT [DF_Alter_Ego_Person_History_History_Date]  DEFAULT (getdate()) FOR [History_Date]
GO

# [DF__ETL_Error__Error__787EE5A0]

In [0]:
ALTER TABLE [dbo].[ETL_Error_Log] ADD  DEFAULT (getdate()) FOR [Error_Timestamp]
GO

# [DF_Gadget_Order_Form_Order_Date]

In [0]:
ALTER TABLE [dbo].[Gadget_Order_Form] ADD  CONSTRAINT [DF_Gadget_Order_Form_Order_Date]  DEFAULT (getdate()) FOR [Order_Date]
GO

# [DF_Gadget_Order_Form_Price_Per_Item]

In [0]:
ALTER TABLE [dbo].[Gadget_Order_Form] ADD  CONSTRAINT [DF_Gadget_Order_Form_Price_Per_Item]  DEFAULT ((0)) FOR [Price_Per_Item]
GO

# [DF_Gadget_Order_Form_Tax]

In [0]:
ALTER TABLE [dbo].[Gadget_Order_Form] ADD  CONSTRAINT [DF_Gadget_Order_Form_Tax]  DEFAULT ((0)) FOR [Tax]
GO

# [DF_Gadget_Order_Form_Shipping]

In [0]:
ALTER TABLE [dbo].[Gadget_Order_Form] ADD  CONSTRAINT [DF_Gadget_Order_Form_Shipping]  DEFAULT ((0)) FOR [Shipping]
GO

# [DF_Gadget_Order_Form_TotalDue]

In [0]:
ALTER TABLE [dbo].[Gadget_Order_Form] ADD  CONSTRAINT [DF_Gadget_Order_Form_TotalDue]  DEFAULT ((0)) FOR [Total_Due]
GO

# [DF__Good_Deed__Good___75A278F5]

In [0]:
ALTER TABLE [dbo].[Good_Deed_History] ADD  DEFAULT (getdate()) FOR [Good_Deed_Timestamp]
GO

# [FK_Alter_Ego_Comic_Universe]

In [0]:
ALTER TABLE [dbo].[Alter_Ego]  WITH CHECK ADD  CONSTRAINT [FK_Alter_Ego_Comic_Universe] FOREIGN KEY([Comic_Universe_ID])
REFERENCES [dbo].[Comic_Universe] ([Comic_Universe_ID])
GO
ALTER TABLE [dbo].[Alter_Ego] CHECK CONSTRAINT [FK_Alter_Ego_Comic_Universe]
GO

# [FK_Alter_Ego_Person_Alter_Ego_ID]

In [0]:
ALTER TABLE [dbo].[Alter_Ego_Person]  WITH CHECK ADD  CONSTRAINT [FK_Alter_Ego_Person_Alter_Ego_ID] FOREIGN KEY([Alter_Ego_ID])
REFERENCES [dbo].[Alter_Ego] ([Alter_Ego_ID])
ON DELETE SET DEFAULT
GO
ALTER TABLE [dbo].[Alter_Ego_Person] CHECK CONSTRAINT [FK_Alter_Ego_Person_Alter_Ego_ID]
GO

# [FK_Alter_Ego_Person_Person_ID]

In [0]:
ALTER TABLE [dbo].[Alter_Ego_Person]  WITH CHECK ADD  CONSTRAINT [FK_Alter_Ego_Person_Person_ID] FOREIGN KEY([Person_ID])
REFERENCES [dbo].[Person] ([Person_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Alter_Ego_Person] CHECK CONSTRAINT [FK_Alter_Ego_Person_Person_ID]
GO

# [FK_Gadget_Order_Form_Corporation]

In [0]:
ALTER TABLE [dbo].[Gadget_Order_Form]  WITH CHECK ADD  CONSTRAINT [FK_Gadget_Order_Form_Corporation] FOREIGN KEY([Corporation_ID])
REFERENCES [dbo].[Corporation] ([Corporation_ID])
GO
ALTER TABLE [dbo].[Gadget_Order_Form] CHECK CONSTRAINT [FK_Gadget_Order_Form_Corporation]
GO

# [FK_Gadget_Order_Form_Gadget]

In [0]:
ALTER TABLE [dbo].[Gadget_Order_Form]  WITH CHECK ADD  CONSTRAINT [FK_Gadget_Order_Form_Gadget] FOREIGN KEY([Gadget_ID])
REFERENCES [dbo].[Gadget] ([Gadget_ID])
GO
ALTER TABLE [dbo].[Gadget_Order_Form] CHECK CONSTRAINT [FK_Gadget_Order_Form_Gadget]
GO

# [FK_Gadget_Order_Form_Person]

In [0]:
ALTER TABLE [dbo].[Gadget_Order_Form]  WITH CHECK ADD  CONSTRAINT [FK_Gadget_Order_Form_Person] FOREIGN KEY([Person_ID])
REFERENCES [dbo].[Person] ([Person_ID])
GO
ALTER TABLE [dbo].[Gadget_Order_Form] CHECK CONSTRAINT [FK_Gadget_Order_Form_Person]
GO

# [CK_Gadget_Order_Form_Number_Ordered]

In [0]:
ALTER TABLE [dbo].[Gadget_Order_Form]  WITH CHECK ADD  CONSTRAINT [CK_Gadget_Order_Form_Number_Ordered] CHECK  (([Number_Ordered]>=(0) AND [Number_Ordered]<(10000)))
GO
ALTER TABLE [dbo].[Gadget_Order_Form] CHECK CONSTRAINT [CK_Gadget_Order_Form_Number_Ordered]
GO